### ISSUE TITLE
Pwned matcher not working in web workers

### ISSUE THREAD

**Issue by michaelhue** [zxcvbn-ts/zxcvbn#100]
I'm using the library inside a web worker without any issues.
When trying to add the `@zxcvbn-ts/matcher-pwned` matcher, an error is thrown due to `window` not being available in the worker context.

The following line causes the issue:
https://github.com/zxcvbn-ts/zxcvbn/blob/d43c54c007bef7f0724daa78e58f02316fb96bde/packages/libraries/pwned/src/haveIBeenPwned.ts#L15-L17

`TextEncoder` is available in workers however.
So changing [lines 15-18](https://github.com/zxcvbn-ts/zxcvbn/blob/d43c54c007bef7f0724daa78e58f02316fb96bde/packages/libraries/pwned/src/haveIBeenPwned.ts#L15-L18)  to something like this should solve the problem:

```js
try {
  return new TextEncoder().encode(text)
} catch (err) {
  throw new Error('No encoder found', { cause: err })
}
```

I'd be happy to provide a pull request if desired.
Thank you!

**Comment by MrWook** [comment]
Interesting, didn't think about webworkers while implementing this.  Here you go https://github.com/zxcvbn-ts/zxcvbn/pull/101

But it will be published in the next major version

**Comment by michaelhue** [comment]
Perfect, thank you! Looking forward to the release. :)

**Comment by MrWook** [comment]
Major version is released
