### ISSUE TITLE
Update Example Documentation

### ISSUE THREAD

**Issue by RacerDelux** [zxcvbn-ts/zxcvbn#103]
The documentation shows using the script tag as a way to implement zxcvbn. The version numbers are out of date. As well the language-common link has an invalid version number.
![image](https://user-images.githubusercontent.com/2667344/153033151-ad4b766b-6f5e-4e41-bdac-db7cc55afa36.png)

https://zxcvbn-ts.github.io/zxcvbn/guide/getting-started/#installation

In addition the code in the example does not work. Using 0.3.0 I was able to get it to run with
```
(function () {
    // all package will be available under zxcvbnts
    const options = {
        translations: zxcvbnts['language-en'].translations,
        graphs: zxcvbnts['language-common'].adjacencyGraphs,
        dictionary: {
            ...zxcvbnts['language-common'].dictionary,
            ...zxcvbnts['language-en'].dictionary,
        },
    }
    zxcvbnts.core.ZxcvbnOptions.setOptions(options)
    console.log(zxcvbnts.core.zxcvbn('AD@gSatOn1Cat!'))
})()
```

**Comment by MrWook** [comment]
Hey, thanks for the report. I'm not really using the script setup so this is much appreciated 👍 
I will adjust the documentation for the next major release. If i'm correct there isn't even a 0.3.0 version for the common language pack 🤦 Which means the documentation has it wrong, too.

Which means i will update the version inside the example for the imported scripts and the correct usage of the functions.

**Comment by MrWook** [comment]
I release the new major version 2.0.0 and updated the documentation according to your findings
