### ISSUE TITLE
TypeError: password.toLowerCase is not a function

### ISSUE THREAD

**Issue by oskar-gmerek** [zxcvbn-ts/zxcvbn#107]
Hi!

I am just trying this amazing library but unfortunately after almost copying / pasting the demo from the docs I get an error.

```
Unhandled Runtime Error
TypeError: password.toLowerCase is not a function
```
From this line:
`zxcvbn(password)`

related line in zxcvbn:
`const passwordLower = password.toLowerCase(); // eslint-disable-next-line complexity`

Im using:
```
    "next": "^12.1.4",
    "react": "^17",
    "react-dom": "^17",
    "@zxcvbn-ts/core": "^2.0.1",
    "@zxcvbn-ts/language-common": "^2.0.1",
    "@zxcvbn-ts/language-en": 
    "typescript": "latest"
```

Do I do anything wrong or it is not compatible with something used?

**Comment by MrWook** [comment]
Hey,

this seems weird can you post your setup and which password is used? 
I would guess that the password that you give to the library is not a string 🤔 
On the other hand this should be catched but maybe it isn't.
So can you double check this on your site if you enter a real string?

**Comment by oskar-gmerek** [comment]
Hey,

@MrWook you are right. It's my fault I pass object instead of string by mistake.

Thanks for help!
