### ISSUE TITLE
Feature Request: Lazy Dictionary Loading

### ISSUE THREAD

**Issue by MatthewAry** [zxcvbn-ts/zxcvbn#11]
zxcvbn is great but the dictionary is huge! When I build my application it would be nice if there was a way to load zxcvbn using a promise, in which it will acquire the dictionary from a CDN, parse and instantiate. This will help reduce application payload sizes for SPA use cases.

**Comment by MrWook** [comment]
The dictionaries are not included in the core library anymore. You need to load them by yourself.

We could add an example in the documentation to show how its done.
For example with webpack you could make an async  import for lazyloading:

```js
import zxcvbn from '@zxcvbn-ts/core'

const loadOptions = async () => {
  const zxcvbnCommonPackage =  import(/* webpackChunkName: "zxcvbnCommonPackage" */ '@zxcvbn-ts/language-common')
  const zxcvbnEnPackage =  import(/* webpackChunkName: "zxcvbnEnPackage" */ '@zxcvbn-ts/language-en')

  return {
    dictionary: {
      ...zxcvbnCommonPackage.dictionary,
      ...zxcvbnEnPackage.dictionary,
    },
    translations: zxcvbnEnPackage.translations,
  }
}

const password = 'somePassword'
const options = await loadOptions()
zxcvbn(password, options)
```

I didn't test it but it should do the trick. With CDN's you would just need to change the imports with `await fetch('somecdn/zxcvbn-ts/language-someLanguage')`.

**Comment by MrWook** [comment]
I looked into it and it seems like there need to be done some changes to the build script to make it work for the browser and CDN approaches.

**Comment by WitteStier** [comment]
The lazy loading as documented did not work for me, however the code below do
```
const loadOptions = async () => {
        const zxcvbnCommonPackage = await import(
          /* webpackChunkName: "zxcvbnCommonPackage" */ '@zxcvbn-ts/language-common'
        );
        const zxcvbnEnPackage = await import(
          /* webpackChunkName: "zxcvbnEnPackage" */ '@zxcvbn-ts/language-en'
        );

        return {
          translations: zxcvbnEnPackage.default.translations,
          dictionary: {
            ...zxcvbnCommonPackage.default.dictionary,
            ...zxcvbnEnPackage.default.dictionary,
          },
        };
      };
```

**Comment by MrWook** [comment]
Thats true thanks for the report i adjusted it https://github.com/zxcvbn-ts/zxcvbn/pull/27

**Comment by MrWook** [comment]
I will close the issue as it is documented how to lazy load dictionaries.
