### ISSUE TITLE
matcher-pwned requests

### ISSUE THREAD

**Issue by dark544** [zxcvbn-ts/zxcvbn#116]
Hey,
when using the pwnd-matcher there is a request for every repeat match.  
Is that intentional?  
Is there a way to prevent that behavior, or is it a bad idea?

**Comment by MrWook** [comment]
Hey, as stated in the [documentation](https://zxcvbn-ts.github.io/zxcvbn/guide/matcher/#matcher-libraries) it is recommended to use the provided debounce function or a debounce function from somewhere else.
There is even a example for the debounce function https://zxcvbn-ts.github.io/zxcvbn/guide/examples/#debounce

**Comment by bwillert** [comment]
I'am using the debounce function.  
But the repeat-matcher executes the pwnd matcher for every repeat I guess.  
  
So when I enter the password "testaa", two requests are sent to the pwnd api:  
"testaa" = "1F390"  in SHA1  
"a" = "86F7E" in SHA1  
  
When I enter "testaabb" I get 3 requests:  
"testaabb" = "C4DCC" in SHA1  
"a" = "86F7E" in SHA1  
"b" = "E9D71" in SHA1

**Comment by MrWook** [comment]
Ah now i understand. This should not be the case i will look into it thanks for the report 👍

**Comment by dark544** [comment]
I don't really know, im not that deep into your library. 😅  
It just seemed odd to me, that there are multiple requests happening.  
For your example there are 6 requests being sent to the pwnd api (P4$$w0rdP4$$w0rd).  
But I guess there is no other way, if you want to partially match a password.
