### ISSUE TITLE
l33t does not work for user input of email address

### ISSUE THREAD

**Issue by U-4-E-A** [zxcvbn-ts/zxcvbn#118]
User input: -
```
const options = {
   dictionary: {
      userInputs: ['mywebsite', 'another@hotmail.com']
   }
}
```
`myw3b$!t3` fails with `"warning: 'There should not be any personal or page related data.'"`
`@noth3r@hotmail.com` passes - no warning, score of 4

Is this a bug in the validation somehow related to the ampersand in a valid email address?

**Comment by MrWook** [comment]
Hey, on the demo page it works just fine 🤔 https://zxcvbn-ts.github.io/zxcvbn/demo/

But i testet it out myself with a little project where i included zxcvbn-ts as a dependency and i get the same issue 🤔 
Interesting issue, i will check it out as soon as i can

**Comment by U-4-E-A** [comment]
Thank you. Awesome package BTW, couldn't work without it. Glad I can contribute something to what has already been built.

**Comment by MrWook** [comment]
@U-4-E-A this bug seems to be in the original version too and it's pretty hard to figure out a neat way so it will take some time
