### ISSUE TITLE
Sequence in ZxcvbnResult should be MatchEstimated[]

### ISSUE THREAD

**Issue by Plebshot** [zxcvbn-ts/zxcvbn#132]
The `sequence` property in the type for `ZxcvbnResult` is of type `MatchExtended[]`. However, I believe this can be `MatchEstimated[]`, which is `MatchExtended & Estimate`. The necessary properties seem to be available on all matches at least.

**Comment by MrWook** [comment]
Good finding. Thats totally correct. The function to get the feedback gets a `sequence` with the type `MatchEstimated[]`. Which is the same sequence as in `ZxcvbnResult`. So currently the type for `sequence` is wrong i will fix it
