### ISSUE TITLE
Missing French lastname source

### ISSUE THREAD

**Issue by MrWook** [zxcvbn-ts/zxcvbn#138]
Unfortunately the french lastname [source](https://www.insee.fr/fr/statistiques/fichier/2540004/nat2019_csv.zip) isn't available anymore.
@jeromes80 do you have another source? I couldn't find any lastname list from the domain

**Comment by jeromes80** [comment]
Hi, it seems they updated the source with newer data :
https://www.insee.fr/fr/statistiques/fichier/2540004/nat2021_csv.zip

Hope it can helps.

**Comment by MrWook** [comment]
Thank you very much 👍
