### ISSUE TITLE
Type 'number' is not assignable to type 'never'.

### ISSUE THREAD

**Issue by IcaroG** [zxcvbn-ts/zxcvbn#162]
If you have in your tsconfig.json the flags noImplicitAny set to false AND strictNullChecks set to true, it's impossible to build this package.

This happens because in `fastest-levenshtein.ts`
```

  const mhc = []
  const phc = []
```
evaluates mhc and phc being of type never[]

Related issue: https://github.com/ka-weihe/fastest-levenshtein/issues/24

**Comment by MrWook** [comment]
What does the build process from fastes-levenshtein has to do with this library? 

I can build this package just fine, so what do you want me to do here?

**Comment by IcaroG** [comment]
After updating the pacakge this error stopped happening. It was happening because our `tsconfig.json` was being applied to node_modules
