### ISSUE TITLE
Missing documentation regarding custom matchers

### ISSUE THREAD

**Issue by danielreiser** [zxcvbn-ts/zxcvbn#163]
First of all, thanks for maintaining this great lib!
As I was building a custom matcher, I was trying to wrap my head around which score to return as the end result score is not deterministically adjusted based on what my matcher is returning. Is it possible to get a bit more insight in how to implement a custom matcher or how the individual properties i, j etc. are taken into account when calculating the score.

Just as a side note I want to implement a custom matcher, which checks agains previous filled inputs in a form (e.g. lowering the score for using personal data in the password). I know userInput but that's not flexible enough for our use-case.

Any help would be greatly appreciated.
Thanks a lot and cheers from Hamburg: ⚓

**Comment by MrWook** [comment]
Hey, this makes total sense to describe all parameter! I will extend to documentation.
But for starters here is a little bit of explanation:

Your matcher needs to return
- pattern
This is just the name of your custom matcher. For example the pwnedMatcher has `pwned`
- i
This is the start index of the matched token
- j
This is the end index of the matched token
- token
This is the token that was matched

For example for the repeat matcher we have this string: `suchARandomRandomPassword`.
This would result in 
i = 5
j = 16
token = RandomRandom
The found token starts at character 5 and ends at character 16

You can extend the return match as you wish if you need any additional information about your matched token. For example the repeat matcher will add a baseGuess, a baseToken and a repeatCount to the object for the scoring function.

The scoring function will get your matcher object and you can define a guess score with the information. 

The lower the score, the worse the password. Thats why the pwned matcher just sets a 1.

If you want to build your own implementation of a userDictionary be aware that the build in dictionary will check for reverse and l33t input too.

To answer your question how the properties are taking into account when calculating the score:
It is totally up to the scoring function and the scoring ist most of the time calculated with extra data from the individual functions like the `repeatCount` of the repeat matcher


Maybe we can extend the userDictionary matcher. What do you think is missing for the matcher?

**Comment by MrWook** [comment]
I added inline desriptions for the typescript types which should help IDEs and some documentation inside vuepress https://github.com/zxcvbn-ts/zxcvbn/pull/166

**Comment by danielreiser** [comment]
Thanks a lot for this detailed explanation! I really appreciate it. I'll think about your question and play a bit with the custom matcher and get back to you :)
