### ISSUE TITLE
RangeError: Maximum call stack size exceeded @zxcvbn-ts/language-en Dictionary

### ISSUE THREAD

**Issue by HarisonLacey** [zxcvbn-ts/zxcvbn#169]
![Screenshot 2023-01-31 at 15 37 16](https://user-images.githubusercontent.com/63789277/215775608-6594be66-ba96-4af9-b02c-b1afa937d55f.png)
![Screenshot 2023-01-31 at 15 40 58](https://user-images.githubusercontent.com/63789277/215776103-70d4dbb8-a68c-4701-a4aa-44c78c8062c0.png)

I am getting a **RangeError: Maximum call stack size exceeded** when using the dictionary in @zxcvbn-ts/language-en for the zxcvbn options. Please see screenshot attached.

Seems to be related to **getRankedDictionariesMaxWordSize**. Please see screenshot attached.

**Comment by simon-abbott** [comment]
I'm getting the same error after upgrading to 2.2.0, only it's causing our app to crash. Downgrading to v2.1.0 fixed it.

**Comment by MrWook** [comment]
Interesting, the maxWorkSize isn't really that expensive and runs in a few ms 🤔 I can't reproduce this issue with my node services and the demo page works fine, too.
So i guess this has something to do with ReactNative 🤔  

Could you give me a simple reproduction repo with ReactNative so i can test it too?

**Comment by simon-abbott** [comment]
> Could you give me a simple reproduction repo with ReactNative so i can test it too?

Here you are: https://github.com/simon-abbott/ZxcvbnRepro

**Comment by iMattPro** [comment]
Same problem here. I don't use React.

**Comment by MrWook** [comment]
@iMattPro what are you using?

**Comment by iMattPro** [comment]
Just vanilla JavaScript via script tags as shown by your documentation.

**Comment by MrWook** [comment]
Alright i found the issue with setting the max stack size for node and a fix for it

**Comment by MrWook** [comment]
The new release is out and it works with a stack size of 81 like before

**Comment by gryffs** [comment]
@MrWook It doesn't look like npm version 2.1.0 has these changes. How do we get these latest changes into npm?  Thanks!

**Comment by simon-abbott** [comment]
@gryffs it was resolved in [@zxcvbn-ts/core@2.2.1](https://github.com/zxcvbn-ts/zxcvbn/releases/tag/%40zxcvbn-ts%2Fcore%402.2.1)

**Comment by gryffs** [comment]
@simon-abbott Thank you! Found it and updated.

**Comment by HarisonLacey** [comment]
@MrWook Sorry about not getting back to you. Thank you for the update, it's very much appreciated!
