### ISSUE TITLE
"Matcher pwned already exists"

### ISSUE THREAD

**Issue by jiblett1000** [zxcvbn-ts/zxcvbn#171]
Hello,

Using the pwned matcher as the Vue example shows  in the docs (code below), results in the console message `Matcher pwned already exists`.

``` js
import matcherPwnedFactory from '@zxcvbn-ts/matcher-pwned'

// optional
const matcherPwned = matcherPwnedFactory(fetch, zxcvbnOptions)
zxcvbnOptions.addMatcher('pwned', matcherPwned)
```

**Comment by MrWook** [comment]
This only happens if add the matcher in a functions that is executed multiple time. I can see that you are using vue and the composition API. So i would assume you are either using it inside a function or your component is rendered multiple time.

If it is rendered multiple time you need to to move the zxcvbn option handling into a place which is only executed once like a plugin

**Comment by jiblett1000** [comment]
@MrWook Thanks for the reply. However, this is the only component I'm using zxcvbn in and I only have one instance of the component in use in my app. This all the zxcvbn code in my component:

``` js
import { zxcvbnAsync, zxcvbnOptions, debounce } from "@zxcvbn-ts/core";
import zxcvbnCommonPackage from "@zxcvbn-ts/language-common";
import zxcvbnEnPackage from "@zxcvbn-ts/language-en";
import matcherPwnedFactory from "@zxcvbn-ts/matcher-pwned";

const matcherPwned = matcherPwnedFactory(fetch, zxcvbnOptions);
zxcvbnOptions.addMatcher("pwned", matcherPwned);

zxcvbnOptions.setOptions({
  translations: zxcvbnEnPackage.translations,
  graphs: zxcvbnCommonPackage.adjacencyGraphs,
  dictionary: {
    ...zxcvbnCommonPackage.dictionary,
    ...zxcvbnEnPackage.dictionary,
  },
  useLevenshteinDistance: true,
});

const debouncedZxcvbn = debounce(async () => {
  if (passwordValue.value) {
    passwordStrength.value = await zxcvbnAsync(passwordValue.value);
  } else {
    passwordStrength.value = null;
  }
}, 300, false);

watch(passwordValue, debouncedZxcvbn);
```

This is in the root of my setup function.

**Comment by jiblett1000** [comment]
...I will try moving the options code to a plugin to see if that helps

**Comment by MrWook** [comment]
I just did the same thing in a nuxt basic setup and it is working fine. So i guess your page is rendered multiple times and on this note... the error would be thrown any way if someone is leaving the password page and access it again. So i need to update the documentation to use a plugin in vue or use it in the app.vue 🤔 

But don't worry too much about the console message, its just a message and it wont break anything. It's just informs you that you are updating the options multiple times which is wasting resources. 
The plugin approach would be something like

```

export default {
  install: () => {
    const matcherPwned = matcherPwnedFactory(fetch, zxcvbnOptions)
    zxcvbnOptions.addMatcher('pwned', matcherPwned)

    const options: OptionsType = {
      // recommended
      dictionary: {
        ...zxcvbnCommonPackage.dictionary,
        ...zxcvbnEnPackage.dictionary,
      },
      // recommended
      graphs: zxcvbnCommonPackage.adjacencyGraphs,
      // recommended
      useLevenshteinDistance: true,
      // optional
      translations: zxcvbnEnPackage.translations,
    }
    zxcvbnOptions.setOptions(options)
  }
}
```

**Comment by jiblett1000** [comment]
@MrWook I'm using nuxt 3. This is my plugin code. Still throwing the error :/

``` js
import { zxcvbnOptions } from "@zxcvbn-ts/core";
import zxcvbnCommonPackage from "@zxcvbn-ts/language-common";
import zxcvbnEnPackage from "@zxcvbn-ts/language-en";
import matcherPwnedFactory from "@zxcvbn-ts/matcher-pwned";

export default defineNuxtPlugin((nuxtApp) => {
  const matcherPwned = matcherPwnedFactory(fetch, zxcvbnOptions);
  zxcvbnOptions.addMatcher("pwned", matcherPwned);

  zxcvbnOptions.setOptions({
    translations: zxcvbnEnPackage.translations,
    graphs: zxcvbnCommonPackage.adjacencyGraphs,
    dictionary: {
      ...zxcvbnCommonPackage.dictionary,
      ...zxcvbnEnPackage.dictionary,
    },
    useLevenshteinDistance: true,
  });
});

```

**Comment by MrWook** [comment]
AH finally i got the same error let me check it a little bit

**Comment by jiblett1000** [comment]
@MrWook Great, thanks! Just good to know I'm not going crazy :)

**Comment by MrWook** [comment]
I got it to work with a nuxtModule and a ready hook:
```
export default function zxcvbnModule(moduleOptions, nuxt) {
  nuxt.hook('ready', async () => {
    const matcherPwned = matcherPwnedFactory(fetch, zxcvbnOptions)
    zxcvbnOptions.addMatcher('pwned', matcherPwned)

    const options: OptionsType = {
      // recommended
      dictionary: {
        ...zxcvbnCommonPackage.dictionary,
        ...zxcvbnEnPackage.dictionary,
      },
      // recommended
      graphs: zxcvbnCommonPackage.adjacencyGraphs,
      // recommended
      useLevenshteinDistance: true,
      // optional
      translations: zxcvbnEnPackage.translations,
    }
    zxcvbnOptions.setOptions(options)
  })
}
```

But be aware that you need to remove all the build folders otherwise the previous code is somehow stuck in there 🤔

**Comment by jiblett1000** [comment]
@MrWook Nevermind in regards to the `fetch` issue. I was still running off of node 16. Switching to 18 fixed that. 

However, I'm still not seeing any fetches to the pwned API.

Now, for some reason I'm also getting a score of 2 when typing in `password` whereas before I was getting a score of 0

**Comment by jiblett1000** [comment]
@MrWook It appears that setting the options in the Nuxt module as per your most recent PR doesn't carry across to runtime. For example, I've set `useLevenshteinDistance: true` in the Nuxt module and if I `console.log(zxcvbnOptions)` afterwards (from within the module), it is correct. However, if I do `console.log(zxcvbnOptions)` from my component, it shows `useLevenshteinDistance: false` .

**Comment by MrWook** [comment]
This makes sense as the module is only executed once on the server side. 
So we need to work with client only plugins. I forgot about them...

The users are not typing any password on the server side rendering anyway. I updated my PR

**Comment by jiblett1000** [comment]
I've put the options back in a client only plugin. This eliminates `Matcher pwned already exists`, but this issue then arises when inputting a password:

```
haveIBeenPwned.ts:33 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'digest')
```

**Comment by MrWook** [comment]
I guess it's because you are working under an unsecure url: 
https://stackoverflow.com/questions/57146558/typeerror-digest-of-undefined-in-development-environment

Nuxt prints out multiple urls to checkout the website like:
> Local:    http://localhost:49537/ 
   Network:  http://192.168.178.218:49537/

Only the localhost address is secure for the browser

**Comment by jiblett1000** [comment]
You are a genius. That did the trick. I was accessing it on my local network. Everything seems to be working as intended now :) Thank you very much for the info.
