### ISSUE TITLE
A demo that can be run offline would be nice

### ISSUE THREAD

**Issue by rdhyee** [zxcvbn-ts/zxcvbn#181]
I'm planning to show https://zxcvbn-ts.github.io/zxcvbn/demo/ to people but am wary of asking people to trust their real passwords with the demo. Is there a way to rewrite the demo so that someone could save the page locally and run the calculation locally (with the network connection off for extra measure)?

**Comment by MrWook** [comment]
The demo is a static page under the gh-page branch. Feel free to copy the branch and run it locally.
But without a network connection you would need to disable the `pwned matcher`.
