### ISSUE TITLE
Tree shaking doesn't seem to work properly

### ISSUE THREAD

**Issue by lekoaf** [zxcvbn-ts/zxcvbn#198]
I did a bundle analysis with the 2.x version where I imported the translations directly from `dist/translations` and then did a new analysis today with the 3.x version where I do `import { translations as enTranslations } from '@zxcvbn-ts/language-en'`

And the sizes got much, much worse as you can see in the image.

![2023-05-08_11-39](https://user-images.githubusercontent.com/7765599/236792258-2af37892-0c59-43fb-8fe8-bfd11161005f.png)

We are happy to help analyse the problem if you'd like, because we really like this project.

**Comment by MrWook** [comment]
True, i think the sideEffects property in the package.json is missing

**Comment by lekoaf** [comment]
Update!

![2023-05-11_08-07](https://github.com/zxcvbn-ts/zxcvbn/assets/7765599/41059b72-db4c-4ac2-a171-f1d0677578f2)

**Comment by codepunkt** [comment]
@lekoaf @MrWook I'm not sure I understand. For me, the Signup chunk checking the password strength has a size of ~2.5 megabytes. Can this get significantly smaller? If yes: How?

**Comment by MrWook** [comment]
@codepunkt do you import more than the translations? Lekoaf is only importing the translations which are small json files.
He is not using the dictionaries which are quite big as you can see.

Be aware that not using the dictionaries is not recommended and will hit the scoring negatively. As most of the scoring comes from comparing the password with those dictionaries. But its up to you if you want to decrease the bundle size of one specific page for password security.

**Comment by codepunkt** [comment]
I'd rather have the dictionaries on server and do the scoring there 🤷🏻

**Comment by lekoaf** [comment]
Yupp, we are only using the translations. The dictionaries were too big for our bundles, especially since we are using several languages, and will add more soon. The repeating patterns etc is good enough for us right now.
