### ISSUE TITLE
MatchSeparator.getSeparatorRegex uses unsupported negative lookbehind in safari

### ISSUE THREAD

**Issue by CuadrosNicolas** [zxcvbn-ts/zxcvbn#202]
We recently to v3 and we noticed error on safari : 

```
Invalid regular expression: invalid group specifier name
```

Turn out the package v3[ uses a the negative lookbehind (?<! )](https://github.com/zxcvbn-ts/zxcvbn/blob/adb801e6be453f44b33dbd1606ceca4283312d59/packages/libraries/main/src/matcher/separator/matching.ts#L39) assertions in the MatchSeparator.getSeparatorRegex static method.
Which is not supported till the [v16.3 of safari](https://caniuse.com/js-regexp-lookbehind).  

For now we only downgraded our package version to 2.2.1 which is working great.
Was this regex assertions mandatory for the new versions ? Is there a way to improve it so that the v3 is compatible with the previous versions of safari ?
Or shall we simply wait for everyone to adopt the latest version of it ?

**Comment by MrWook** [comment]
Nice to know. I don't really use safari but it seems like the android chrome only recently added it too.
So we should remove the lookbehind. I think it should work somehow even if it is not working as good as before.
I will take a look
