### ISSUE TITLE
One to many l33t substitutions aren't supported

### ISSUE THREAD

**Issue by zeezooz** [zxcvbn-ts/zxcvbn#204]
https://github.com/zxcvbn-ts/zxcvbn/blob/adb801e6be453f44b33dbd1606ceca4283312d59/packages/libraries/main/src/matcher/dictionary/variants/matching/unmunger/TrieNode.ts#L22
replaces the substitutions instead of adding, so when a l33tTable has
```
  g: ['9'],
  q: ['9'],
```
TrieNode from l33tTableToTrieNode will have only 9 -> q.

On the other hand, fixing it breaks the test for
https://github.com/zxcvbn-ts/zxcvbn/blob/adb801e6be453f44b33dbd1606ceca4283312d59/packages/libraries/main/test/matching.spec.ts#L22
because it has 2592 variants with the default l33tTable, but the limit is lower, so the first 0 isn't replaced and the first word doesn't match.

**Comment by zeezooz** [comment]
Do we really need partially substituted passwords from getCleanPasswords?
When it returns only variants with full substitution, there are only 16 results for 'r0sebudmaelstrom11/20/91aaaa' and it passes all the tests except for getCleanPasswords itself.

**Comment by MrWook** [comment]
Hey thank you for the issues and the bug fix.

It seems like you already tried it, so please open a PR for it and i will look into it
