### ISSUE TITLE
L33t scoring is incorrect for multisymbol substitutions

### ISSUE THREAD

**Issue by zeezooz** [zxcvbn-ts/zxcvbn#211]
The code
https://github.com/zxcvbn-ts/zxcvbn/blob/7c5fe5aeed8a74b7c305394db1f702a1e71dd558/packages/libraries/main/src/matcher/dictionary/variants/scoring/l33t.ts#L17-L22
assumes that both `sub.substitution` and `sub.letter` are 1 character long, which may not be correct. In this case, the scoring is incorrect.

**Comment by MrWook** [comment]
Hey, thanks again 👍 

I checked it, and i can't seem to find a difference. Can you give me an example where the change would change the scoring?

**Comment by zeezooz** [comment]
To see the difference, the password must have both parts of PasswordChanges and at least one of them more than once. For example, "wwwpassvvord" has "vv" and several "w".
