### ISSUE TITLE
Regex matcher returns only first match

### ISSUE THREAD

**Issue by zeezooz** [zxcvbn-ts/zxcvbn#213]
https://github.com/zxcvbn-ts/zxcvbn/blob/7c5fe5aeed8a74b7c305394db1f702a1e71dd558/packages/libraries/main/src/matcher/regex/matching.ts#L22-L23
will execute the regex only once. Is this intentional? The other matchers seem to return all possible matches.
And it returns all matches in the Dropbox version:
https://github.com/dropbox/zxcvbn/blob/master/src/matching.coffee#L416

**Comment by MrWook** [comment]
No this isn't intentional. I made a PR for it
