### ISSUE TITLE
One of the directions gets less turns and guesses in spatial matcher

### ISSUE THREAD

**Issue by zeezooz** [zxcvbn-ts/zxcvbn#219]
turns became 0 in
https://github.com/zxcvbn-ts/zxcvbn/blob/0ebc6ff1fb909e50678d07868cba61531da9f25f/packages/libraries/main/test/matcher/spatial/matching.spec.ts#L48
Is there a reason for this? It's 1 in the Dropbox version and it looks like it should be 1 according to the comments in the code, which will give the same score for all directions.

**Comment by MrWook** [comment]
yes there is a small variable initialization issue. 
Good finding!
