### ISSUE TITLE
Typing issue

### ISSUE THREAD

**Issue by MichaelAlt** [zxcvbn-ts/zxcvbn#227]
https://github.com/zxcvbn-ts/zxcvbn/blob/ce3aed62ab3e95ebf89cec0ece737eb8579149a9/packages/libraries/main/src/matcher/spatial/matching.ts#L44

Leads to typing error in v3.0.3
![image](https://github.com/zxcvbn-ts/zxcvbn/assets/5499575/d3223e9d-d148-42d9-881f-724e490f31bb)

**Comment by MrWook** [comment]
Hey thank you for the issue but shouldn't you exclude the node_modules folder with the tsconfig?

**Comment by MichaelAlt** [comment]
Yey you are correct it was an "accidential find" :) Our karma tests failed even though node_modules ist excluded in our tsconfig. The error is only shown because we have `noImplicityAny: false` set in the tsconfig.
