### ISSUE TITLE
Source for polish first and last names is missing

### ISSUE THREAD

**Issue by mimi89999** [zxcvbn-ts/zxcvbn#273]
Hello,

@oskar-gmerek I noticed that the README for the polish dictionary https://github.com/zxcvbn-ts/zxcvbn/blob/master/packages/languages/pl/README.md links to https://github.com/oskar-gmerek/polish_database, however that repo is not publicly accessible.

**Comment by MrWook** [comment]
The readme of the polish language package need to be cleaned definitely but the repo from oska-gmerek isn't used anyway so it's not that big of a deal and more of a documentation issue. But thank you for pointing this out!
