### ISSUE TITLE
Custom matcher

### ISSUE THREAD

**Issue by MrWook** [zxcvbn-ts/zxcvbn#33]
There was some issues and requests to have more simple matchers like `password min length`.
In my opinion this is nothing this library should handle because zxcvbn is intended to get rid of the old paradigm  "passwords must contain three of {lower, upper, numbers, symbols}"

On the other hand i know people will still add those checks in addition to zxcvbn. Therefore we could simplify things and add an option to add custom matchers.

**Comment by Tostino** [comment]
This is another feature I wanted to support in nbvcxz.

For nbvcxz, each "match" has to implement this interface: https://github.com/GoSimpleLLC/nbvcxz/blob/master/src/main/java/me/gosimple/nbvcxz/matching/match/Match.java
and each "matcher" has to implement this one: https://github.com/GoSimpleLLC/nbvcxz/blob/master/src/main/java/me/gosimple/nbvcxz/matching/PasswordMatcher.java

So anyone can pull in nbvcxz and implement a custom matcher / match type that does whatever specific thing I didn't think of, and calculates entropy whatever way the user makes it work. They just need to use the configuration to specify that custom matcher should also be used, as by default we only run with the matchers provided with nbvcxz. 

I specifically didn't make it easy to do things like a "min length", but it is still possible to do if they wanted to. You could just specify a "MinLengthMatcher" that will match to whole passwords if they are < some length, and a corresponding "MinLengthMatch" that calculates 0 (or some really low) entropy value.

After typing all this out, I see you already have a PR that you have done a good bit of this work. So likely this info is unnecessary =).

**Comment by MrWook** [comment]
Hey thanks for the insides anyway :) 

Here it will be fairly easy to use custom matcher because everybody could just add more matchers in an array :D
In a perferct wolrd i would like to let the users use the custom matcher without adding a scoring to their matchers. This way they could add feedback for the password without changing the scoring but this seems to be a bit difficult.
 
When i have time again, i will probably fix the types in my PR and merge it.
