### ISSUE TITLE
Road to 1.0.0

### ISSUE THREAD

**Issue by MrWook** [zxcvbn-ts/zxcvbn#36]
At some point this project should have a full release for 1.0.0.
Therefore i places a milestone on some issues and PR that are needed to be included to minimise the Breaking changes after the release.

- internal types should be fixed => types fixed
- ~~Have i Been Pwned API Support => will result in a the api change because this is async~~
- add some feedback for userinput dictionaries => nice to have
- The documentation need some spelling, grammar improvements
- Maybe add custom matcher => would add a new option
- add async matcher support

**Comment by paulverbeke** [comment]
Hi,
First of all thanks a lot for this work. The original Dropbox library desperately needed maintenance.

I saw that french translations were recently added by someone, in looking into this I noticed that, no matter the language, the only feedback given when password contains an entry from the userInputs dictionary is 'There should not be any personal data.'.
Based on the original library documentation, this dictionary should also be used for site-specific vocabulary, so can I suggest that this feedback be changed to something more representative of what the dev is likely to have added, in the line of "There should not be any personal data or forbidden/banned words", or just a more general feedback ?

I can take care of updating french translations of needed.

Thanks !

**Comment by MrWook** [comment]
I'm all open for better translations, do you mind moving this into an own issue. Seems like a good idea but `forbidden/banned words` seems not to fit. As a user i would be confused if i see this. How should the user know whats forbidden or not. 
Let's discuess this an the issue

**Comment by paulverbeke** [comment]
sure

**Comment by MrWook** [comment]
1.0.0 is released
