### ISSUE TITLE
Improving userInputs dictionnary feedback

### ISSUE THREAD

**Issue by paulverbeke** [zxcvbn-ts/zxcvbn#52]
Hi,
First of all thanks a lot for this work. The original Dropbox library desperately needed maintenance.

I saw that french translations were recently added by someone, in looking into this I noticed that, no matter the language, the only feedback given when password contains an entry from the userInputs dictionary is 'There should not be any personal data.'.
Based on the original library documentation, this dictionary should also be used for site-specific vocabulary, so can I suggest that this feedback be changed to something more representative of what the dev is likely to have added, in the line of "There should not be any personal data or forbidden/banned words", or just a more general feedback ?

I can take care of updating french translations if needed.

Thanks !

_Originally posted by @paulverbeke in https://github.com/zxcvbn-ts/zxcvbn/issues/36#issuecomment-844738592_

**Comment by paulverbeke** [comment]
Could we just list every forbidden words ? "There should not be any of these words: [...]" and enumerating userInputs list

**Comment by MrWook** [comment]
The list would be pretty weird and can get pretty quick out of hand. The dev already has full control of what is shown as feedback, as you can just edit the array of it:
```
import zxcvbnEnPackage from '@zxcvbn-ts/language-en'

const translations = zxcvbnEnPackage.translations
translations.warnings.userInputs = 'Your custom feedback for userInputs'
```

How about something like "There should not be any personal or page related data."?

**Comment by paulverbeke** [comment]
oh great, didn't realize you could override. In this case yes the feedback is definitely better like this. I would emphasize something like "service" or "site" instead of "page"

**Comment by MrWook** [comment]
You can override most of the stuff that was my goal. 
Let's stick with `site`. Which means we have those translations:

en:
`There should not be any personal or page related data.`

de:
`Es sollten keine persönlichen oder Seiten relevanten Daten vorkommen.`

fr:
Your translation

nl-be:
@SimonBackx do you mind helping us out?

**Comment by paulverbeke** [comment]
Great, for the `fr` part that should be: `Le mot de passe ne doit pas comporter de données personnelles ou liées au site.`

**Comment by MrWook** [comment]
Do you mind creating a PR for it? 
Since Simon does not answer we can just use something like deepl for nl-be and someone can improve it later.
This way we can get this issue rolling 👍
