### ISSUE TITLE
Usage with import maps

### ISSUE THREAD

**Issue by zzeligg** [zxcvbn-ts/zxcvbn#72]
How would one use this library through import maps?

I tried to add it to my importmap, as follows

`{ "imports": {  "zxcvbn-ts": "/js/zxcvbn-ts.js"  } }`

Then, in another module:

`import { zxcvbn, ZxcvbnOptions } from 'zxcvbn-ts'`

The `zxcvbn-ts.js` file itself is correctly fetched by the browser, but since the code is wrapped inside an anonymous function which does not get executed (because it's fetched as a module), then the exports are not defined. 

I am not very familiar with all the bundling/import methods of Javascript modules, but is there a way to use zxcvbn-ts with import maps? Or am I missing something?

I do not want to use any bundler, I only want to use ES6 modules with import maps.

**Comment by MrWook** [comment]
hey, i never used import maps before but if you talk about ES6 modules than `zxcvbn-ts.js` is the wrong file. This file is for simple browser fetching with the script tag.
If you want to have the esm package you would need to import `index.esm.js` but this files imports other files as well and i don't know how this is gonna work with import maps.

**Comment by MrWook** [comment]
I close this issue because there isn't a response and i don't think that this is related to zxcvbn-ts
