### ISSUE TITLE
Enable adding user inputs to the dictionary on-the-fly through core function args

### ISSUE THREAD

**Issue by netanel-haber** [zxcvbn-ts/zxcvbn#76]
The original library allows passing in user inputs to the actual core function (the one you would call with a password). This port instead allows passing said inputs through the SetOptions interface, which is a valid design decision. 

It would be convenient to also allow the old way, for the following reason: Creating the Options argument may involve costly work in some workflows - including dynamically importing the language packs, and creating the actual dictionary, for example. 

Providing this additional interface can allow us to decouple the work needed in order create the initial options object from the much lighter work of handling constantly changing user input.

I can take a look at the code later and maybe submit a pull request if you think this is too much trouble.

**Comment by MrWook** [comment]
Hey, i kinda get what you mean. 
If you have a form for a registration and you want that the password is not allowed to be one of the values of every input field you would need to update the options on every blur from the input fields.
Didn't think about this one.

To get this work without performance issues, we would need to add a new function to extend the dictionaries on the fly.
