### ISSUE TITLE
Enable type narrowing on core function result

### ISSUE THREAD

**Issue by netanel-haber** [zxcvbn-ts/zxcvbn#77]
The current implementation of the core function is:
```typescript 
export const zxcvbn = (
  password: string,
): ZxcvbnResult | Promise<ZxcvbnResult> => {
  const matching = new Matching()

  const start = time()

  const matches = matching.match(password)

  if (matches instanceof Promise) {
    return matches.then((resolvedMatches) => {
      return createReturnValue(resolvedMatches, password, start)
    })
  }
  return createReturnValue(matches, password, start)
}
```

#### Summary
The typing of the return type is a union: Either a result, or a promise wrapping a result. Narrowing this using generics for example may improve usage cleanliness.

#### Explanation

This union is necessary because matchers may be asynchronous:
```typescript
const usedMatcher = new Matcher()
const result = usedMatcher.match({
  password,
  omniMatch: this,
})

if (result instanceof Promise) {
  result.then((response) => {
    extend(matches, response)
  })
  promises.push(result)
} else {
  extend(matches, result)
}
```

This is all well and good, but currently at compile time we know that all of the builtin matchers are synchronous.

```typescript
  readonly matchers: Matchers = {
    date: dateMatcher,
    dictionary: dictionaryMatcher,
    regex: regexMatcher,
    repeat: repeatMatcher,
    sequence: sequenceMatcher,
    spatial: spatialMatcher,
  }
```

So as of now, only user submitted matchers can be asynchronous. I'd guess that most of the libraries users don't create custom matchers, and even when they do they wouldn't necessarily make them async. So forcing all users of the library to deal with a promise-wrapped value is unfortunate (It is possible that new builtin async matchers are planned in the **short term future** - that would make my point irrelevant).

Allowing type narrowing using generics, say, where a generic argument may be the type of the matchers passed to the options interface, may be a simple solution that doesn't require recoding the entire typings of the library.

NOTE
It should also be added that the asynchronous nature of the function is currently not mentioned anywhere in the docs, so if the state of the function should remain the same an update of the docs is in order.

If this seems like alot of work to the maintainer(s) of the library, I could look into submitting a pull request.

**Comment by MrWook** [comment]
Hey, to be honest i'm not that good with typescript i only can handle the basic stuff. So i would love to get a pull request to improve the type handling.

I can tell you that there won't be any default async matchers in the core library. Those would be added separately as an independent package like https://github.com/zxcvbn-ts/zxcvbn/pull/66
This means i should improve the documentation and state that the core library supports async matchers but has no by default 👍

**Comment by MrWook** [comment]
The generic type is kind of a pain and doesn't really work without a parameter that determine the async behavior therefore i will split the sync and async function into two separated ones.
