### ISSUE TITLE
Dummy translation keys file part of the build.

### ISSUE THREAD

**Issue by JonL1** [zxcvbn-ts/zxcvbn#81]
Is there any reason why this file is part of the build? 

https://github.com/zxcvbn-ts/zxcvbn/blob/master/packages/libraries/main/src/data/translationKeys.ts

I assume it's just a dummy file that should serve as a template. Depending on how you load the scripts it can happen that these dummy keys are loaded instead of the right ones messing up the UI.

![image](https://user-images.githubusercontent.com/1325712/145205567-8de44e34-5233-4570-8816-2f027e843dfe.png)

**Comment by JonL1** [comment]
No need for changes. I found i sneaky bug in my code.

**Comment by MrWook** [comment]
Actually just for future reference, those keys are for people that have their own translation system. This was requested a lot in the original repository.
